name: Deploy Next.js Docker to Droplet

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build & push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gftherd24/netflix-demo-frontend:latest

      # 4️⃣ Add Droplet to known_hosts
      - name: Add Droplet to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_DROPLET_IP }} >> ~/.ssh/known_hosts

      # 5️⃣ Deploy via SSH
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying app..."
            mkdir -p ${{ secrets.APP_PATH }}
            cd ${{ secrets.APP_PATH }}
            docker pull gftherd24/netflix-demo-frontend:latest
            docker-compose down || echo "docker-compose down failed"
            docker-compose up -d
            echo "Deployment completed!"
